aboutme/urls.py
from django.urls import path
from .views import index, experiences, portofolio, contact

app_name = 'aboutme'
urlpatterns = [
    path('', index, name='index'),
    path('experiences', experiences, name='experiences'),
    path('portofolio', portofolio, name='portofolio'),
    path('contact', contact, name='contact'),
]

config/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('aboutme/', include('aboutme.urls')),
    path('users/', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from home.views import index

urlpatterns = [
    path('', index, name='index'),
    path('login', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='logout.html'), name='logout')
]

dashboard/urls.py
from django.urls import path
from dashboard.views import index

app_name = 'dashboard'
urlpatterns = [
    path('', index, name='index'),
]

users/urls.py
from django.urls import path
from .views import register

app_name = 'users'
urlpatterns = [
    path('register', register, name='register')
]

dashboard/models.py
from django.db import models

# Create your models here.

aboutme/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'aboutme/index.html', {})


def contact(request):
    return render(request, 'aboutme/contact.html', {})


def experiences(request):
    return render(request, 'aboutme/experiences.html', {})


def portofolio(request):
    return render(request, 'aboutme/portofolio.html', {})

authentication/views.py
from django.shortcuts import render

# Create your views here.

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    return render(request, 'dashboard/index.html', {})

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html', {})

users/views.py
from django.shortcuts import render


def register(request):
    return render(request, 'users/register.html', {})

aboutme/templates/aboutme/contact.html
{% extends "front/base.html" %}

{% block head_title %}
About Me - Contact Me
{% endblock head_title %}

{% block main_contents %}
<h2>Contact Me</h2>
{% endblock main_contents %}

aboutme/templates/aboutme/experiences.html
{% extends "front/base.html" %}

{% block head_title %}
About Me - Experiences
{% endblock head_title %}

{% block main_contents %}
<h2>Experiences</h2>
{% endblock main_contents %}

aboutme/templates/aboutme/portofolio.html
{% extends "front/base.html" %}

{% block head_title %}
About Me - Portofolio
{% endblock head_title %}

{% block main_contents %}
<h2>Portofolio</h2>
{% endblock main_contents %}

authentication/templates/login.html
{% extends "front/base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
Login
{% endblock head_title %}

{% block main_contents %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method='POST'> {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Log In</legend>
                    {{ form | crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock main_contents %}

authentication/templates/logout.html
{% extends "front/base.html" %}

{% block head_title %}
Logout
{% endblock head_title %}

{% block main_contents %}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2 class="text-capitalize">you have been logged out</h2>
            <div class="border-top pt-3">
                <small class="text-muted">
                    <a href="{% url 'login' %}">Log In Again</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock main_contents %}

templates/base.html
<!doctype html>
<html>

<head>
    <title>Lei Hua - {% block head_title %}Base{% endblock head_title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include "base/css.html" %}
</head>

<body>
    <button id="btnScrollToTop">
        <i class="material-icons">arrow_upward</i>
    </button>
    {% include "base/navbar.html" %}

    {% block main_contents %}
    {% endblock main_contents %}

    {% include "base/js.html" %}
</body>

</html>

templates/dashboard/base.html
{% load static %}

<!doctype html>
<html>

<head>
    <title>Dashboard Template - {% block head_title %}Base{% endblock head_title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include "dashboard/base/css.html" %}
</head>

<body>

    <button id="btnScrollToTop">
        <i class="material-icons">arrow_upward</i>
    </button>

    {% include "dashboard/base/navbar.html" %}
    <div class="wrapper d-flex">
        {% include "dashboard/base/sidebar.html" %}
        <div class="content">
            <main>
                {% block main_contents %}
                {% endblock main_contents %}
            </main>
        </div>
    </div>

    {% include "dashboard/base/js.html" %}
</body>

</html>

templates/dashboard/base/css.html
{% load static %}

<link rel="shortcut icon" href="{% static 'img/icons/favicons/dashboard.png' %}" type="image/png">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/colors.css' %}">
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

templates/dashboard/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.min.js"></script>

<script src="{% static 'js/backtotop.js'%}"></script>
<script src="{% static 'js/dashboard/site.js'%}"></script>

templates/dashboard/base/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-color-blue-grey-dark-200 sticky-top">
    <button class="navbar-toggler sideMenuToggler" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Dashboard</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto ml-5">
            <li class="nav-item active">
                <button type="button"
                    class="btn btn-sm d-flex align-items-center p-1 bg-color-blue-grey-600 text-white sideMenuToggler"
                    id="switcher">
                    <span class="material-icons">swap_horiz</span>
                </button>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Front Home <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="myaccount" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <img src="{% static 'img/users/avatar.png' %}" class="rounded-circle avatar" width="26" height="26"
                        alt="">
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="myaccount">
                    <div class="text-center">
                        <img src="{% static 'img/users/avatar.png' %}" class="rounded-circle avatar" alt="" width="50"
                            height="50">
                        <p class="h6 text-primary py-2">{{ user.first_name }}</p>
                        <div class="dropdown-divider"></div>
                    </div>
                    <a class="dropdown-item" href="#">My Profile</a>
                    <a class="dropdown-item" href="#">Change Password</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/dashboard/base/sidebar.html
{% load static %}


<div class="sideMenu bg-color-blue-grey-200 ">
    <div class="sidebar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="nav-link px-2">
                    <i class="material-icons icon">dashboard</i>
                    <span class="text">Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link px-2">
                    <i class="material-icons icon">person</i>
                    <span class="text">User Profile</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link px-2">
                    <i class="material-icons icon">insert_chart</i>
                    <span class="text">Charts</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link px-2">
                    <i class="material-icons icon">settings</i>
                    <span class="text">Settings</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link px-2">
                    <i class="material-icons icon">computer</i>
                    <span class="text">Demo</span>
                </a>
            </li>
        </ul>
    </div>
</div>

templates/front/base.html
<!doctype html>
<html>

<head>
    <title>Lei Hua - {% block head_title %}Base{% endblock head_title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include "front/base/css.html" %}
</head>

<body>
    <button id="btnScrollToTop">
        <i class="material-icons">arrow_upward</i>
    </button>
    {% include "front/base/navbar.html" %}

    {% block main_contents %}
    {% endblock main_contents %}

    {% include "front/base/js.html" %}
</body>

</html>

templates/front/base/css.html
{% load static %}

<link rel="shortcut icon" href="{% static 'img/icons/favicon/front.png' %}" type="image/png">

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/colors.css'%}">
<link rel="stylesheet" href="{% static 'css/site.css'%}">

templates/front/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.0.slim.min.js"
    integrity="sha256-ZaXnYkHGqIhqTbJ6MB4l9Frs/r7U4jlx7ir8PJYBqbI=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>

<script src="{% static 'js/backtotop.js'%}"></script>
<script src="{% static 'js/front/site.js' %}"></script>

templates/front/base/navbar.html
{% load static %}
{% load datetime_tags %}

<div class="header bg-white py-2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-4 logo">
                Lei Hua
            </div>
            <div class="col-sm-12 col-md-8 text-right">
                <ul class="nav justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Active</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <form class="form-inline my-lg-0">
                        <div class="form-group">
                            <div class="input-group">
                                <input type="search" class="form-control  input-sm border-right-0 border"
                                    name="title_contains">
                                <span class="input-group-append">
                                    <div class="input-group-text bg-transparent">
                                        <i class="material-icons">search</i>
                                    </div>
                                </span>
                            </div>
                        </div>
                    </form>
                </ul>
            </div>
        </div>
        <!--/row-->
    </div>
    <!--container-->
</div>
<nav class="navbar navbar-expand-md navbar-dark sticky-top bg-color-blue-grey-200 mb-3">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="aboutme" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">About Me</a>
                <div class="dropdown-menu" aria-labelledby="aboutme">
                    <a class="dropdown-item" href="{% url 'aboutme:index'%}">Overview</a>
                    <a class="dropdown-item" href="{% url 'aboutme:experiences'%}">My Experiences</a>
                    <a class="dropdown-item" href="{% url 'aboutme:portofolio'%}">My Portofolio</a>
                    <a class="dropdown-item" href="{% url 'aboutme:contact'%}">Contact Me</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
            {% if user.is_authenticated  %}
            <li class="nav-item">
                <a class="nav-link text-white" href="#">Good {% time_of_day %} {{ user.first_name }}</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="myaccount" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <img src="{% static 'img/users/avatar.png' %}" class="rounded-circle avatar" width="26" height="26"
                        alt="">
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="myaccount">
                    <a class="dropdown-item" href="{% url 'dashboard:index' %}">Dashboard</a>
                    <a class="dropdown-item" href="#">My Profile</a>
                    <a class="dropdown-item" href="#">Change Password</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="myaccount" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <img src="{% static 'img/users/avatar.png' %}" class="rounded-circle avatar" width="26" height="26"
                        alt="">
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="myaccount">
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'users:register' %}">Register</a>
                </div>
            </li>
            {% endif %}

        </ul>

    </div>
</nav>

users/templates/users/register.html
{% extends "front/base.html" %}

{% block head_title %}
Register
{% endblock head_title %}

{% block main_contents %}
<h2>Register</h2>
{% endblock main_contents %}